#!/usr/bin/env bash
set -euo pipefail
cd /mnt/sda/wanght19/code/SVD/DiffuModel/SeqDiffuSeq
/mnt/sda/wanght19/anaconda3/envs/FVD-DPM/bin/python codediffpro/train_minimal.py \
  --dataset activemq \
  --data-dir codediff/data/lineDP_dataset \
  --tokenizer-json codediff/data/lineDP_dataset/activemq_bpe/tokenizer.json \
  --exp-name activemq_codediffpro_fixedmax_ep20_eval1_20260408 \
  --batch-size 8 \
  --num-epochs 20 \
  --eval-every 1 \
  --save-every 1 \
  --num-workers 0 \
  --lr 0.0001 \
  --weight-decay 0.0 \
  --max-tokens-per-line 48 \
  --max-lines-per-file -1 \
  --line-window-size 256 \
  --line-window-stride 64 \
  --balanced-sampling \
  --diffusion-steps 1 \
  --token-emb-dim 128 \
  --line-hidden-dim 128 \
  --cond-dim 256 \
  --label-emb-dim 256 \
  --num-cond-layers 2 \
  --num-denoise-layers 2 \
  --nhead 8 \
  --dropout 0.1 \
  --consistency-weight 0.1 \
  --proto-weight 1.2 \
  --proto-temperature 0.07 \
  --proto-margin 0.2 \
  --proto-pos-weight 3.0 \
  --proto-neg-weight 1.0 \
  --ranking-weight 1.0 \
  --ranking-margin 0.4 \
  --hard-negative-ratio 0.3 \
  --hard-negative-weight 0.7 \
  --hard-negative-margin 0.1 \
  --tau 0.0 \
  --tau-mode auto \
  --tau-candidates 81 \
  --seed 0 \
  --device cpu \
  --save-all-checkpoints
